--
-- Arquivo gerado com SQLiteStudio v3.4.21 em sáb jul 4 17:45:07 2026
--
-- Codificação de texto usada: System
--
-- Resultados da consulta:
-- 
	CREAT VIEW Premier_League_2021 AS
	SELECT 
--     hometeam AS home_team,
--     awayteam AS away_team, CONCAT(CAST(FTHG AS INTEGER), ' x ', CAST(FTAG AS INTEGER)) AS score,
--     fthg AS home_team_goals, 
--     ftag AS away_team_goals, 
--     CASE
--          WHEN FTR = 'A'
--          THEN 'Lose'
--          WHEN FTR = 'H'
--          THEN 'Win'
--          ELSE 'Draw'
--          END as result
-- FROM divisions as d
-- LEFT JOIN matchs as m
-- on d.division = m.div
-- WHERE name = 'Premier League' and season = 2021
--
BEGIN TRANSACTION;
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Arsenal', 'Aston Villa', '0 x 3', 0.0, 3.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Arsenal', 'Brighton', '2 x 0', 2.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Arsenal', 'Burnley', '0 x 1', 0.0, 1.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Arsenal', 'Chelsea', '3 x 1', 3.0, 1.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Arsenal', 'Crystal Palace', '0 x 0', 0.0, 0.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Arsenal', 'Everton', '0 x 1', 0.0, 1.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Arsenal', 'Fulham', '1 x 1', 1.0, 1.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Arsenal', 'Leeds', '4 x 2', 4.0, 2.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Arsenal', 'Leicester', '0 x 1', 0.0, 1.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Arsenal', 'Liverpool', '0 x 3', 0.0, 3.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Arsenal', 'Man City', '0 x 1', 0.0, 1.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Arsenal', 'Man United', '0 x 0', 0.0, 0.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Arsenal', 'Newcastle', '3 x 0', 3.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Arsenal', 'Sheffield United', '2 x 1', 2.0, 1.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Arsenal', 'Southampton', '1 x 1', 1.0, 1.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Arsenal', 'Tottenham', '2 x 1', 2.0, 1.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Arsenal', 'West Brom', '3 x 1', 3.0, 1.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Arsenal', 'West Ham', '2 x 1', 2.0, 1.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Arsenal', 'Wolves', '1 x 2', 1.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Aston Villa', 'Arsenal', '1 x 0', 1.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Aston Villa', 'Brighton', '1 x 2', 1.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Aston Villa', 'Burnley', '0 x 0', 0.0, 0.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Aston Villa', 'Chelsea', '2 x 1', 2.0, 1.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Aston Villa', 'Crystal Palace', '3 x 0', 3.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Aston Villa', 'Everton', '0 x 0', 0.0, 0.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Aston Villa', 'Fulham', '3 x 1', 3.0, 1.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Aston Villa', 'Leeds', '0 x 3', 0.0, 3.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Aston Villa', 'Leicester', '1 x 2', 1.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Aston Villa', 'Liverpool', '7 x 2', 7.0, 2.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Aston Villa', 'Man City', '1 x 2', 1.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Aston Villa', 'Man United', '1 x 3', 1.0, 3.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Aston Villa', 'Newcastle', '2 x 0', 2.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Aston Villa', 'Sheffield United', '1 x 0', 1.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Aston Villa', 'Southampton', '3 x 4', 3.0, 4.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Aston Villa', 'Tottenham', '0 x 2', 0.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Aston Villa', 'West Brom', '2 x 2', 2.0, 2.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Aston Villa', 'West Ham', '1 x 3', 1.0, 3.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Aston Villa', 'Wolves', '0 x 0', 0.0, 0.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Brighton', 'Arsenal', '0 x 1', 0.0, 1.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Brighton', 'Aston Villa', '0 x 0', 0.0, 0.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Brighton', 'Burnley', '0 x 0', 0.0, 0.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Brighton', 'Chelsea', '1 x 3', 1.0, 3.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Brighton', 'Crystal Palace', '1 x 2', 1.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Brighton', 'Everton', '0 x 0', 0.0, 0.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Brighton', 'Fulham', '0 x 0', 0.0, 0.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Brighton', 'Leeds', '2 x 0', 2.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Brighton', 'Leicester', '1 x 2', 1.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Brighton', 'Liverpool', '1 x 1', 1.0, 1.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Brighton', 'Man City', '3 x 2', 3.0, 2.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Brighton', 'Man United', '2 x 3', 2.0, 3.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Brighton', 'Newcastle', '3 x 0', 3.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Brighton', 'Sheffield United', '1 x 1', 1.0, 1.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Brighton', 'Southampton', '1 x 2', 1.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Brighton', 'Tottenham', '1 x 0', 1.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Brighton', 'West Brom', '1 x 1', 1.0, 1.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Brighton', 'West Ham', '1 x 1', 1.0, 1.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Brighton', 'Wolves', '3 x 3', 3.0, 3.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Burnley', 'Arsenal', '1 x 1', 1.0, 1.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Burnley', 'Aston Villa', '3 x 2', 3.0, 2.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Burnley', 'Brighton', '1 x 1', 1.0, 1.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Burnley', 'Chelsea', '0 x 3', 0.0, 3.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Burnley', 'Crystal Palace', '1 x 0', 1.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Burnley', 'Everton', '1 x 1', 1.0, 1.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Burnley', 'Fulham', '1 x 1', 1.0, 1.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Burnley', 'Leeds', '0 x 4', 0.0, 4.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Burnley', 'Leicester', '1 x 1', 1.0, 1.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Burnley', 'Liverpool', '0 x 3', 0.0, 3.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Burnley', 'Man City', '0 x 2', 0.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Burnley', 'Man United', '0 x 1', 0.0, 1.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Burnley', 'Newcastle', '1 x 2', 1.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Burnley', 'Sheffield United', '1 x 0', 1.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Burnley', 'Southampton', '0 x 1', 0.0, 1.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Burnley', 'Tottenham', '0 x 1', 0.0, 1.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Burnley', 'West Brom', '0 x 0', 0.0, 0.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Burnley', 'West Ham', '1 x 2', 1.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Burnley', 'Wolves', '2 x 1', 2.0, 1.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Chelsea', 'Arsenal', '0 x 1', 0.0, 1.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Chelsea', 'Aston Villa', '1 x 1', 1.0, 1.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Chelsea', 'Brighton', '0 x 0', 0.0, 0.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Chelsea', 'Burnley', '2 x 0', 2.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Chelsea', 'Crystal Palace', '4 x 0', 4.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Chelsea', 'Everton', '2 x 0', 2.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Chelsea', 'Fulham', '2 x 0', 2.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Chelsea', 'Leeds', '3 x 1', 3.0, 1.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Chelsea', 'Leicester', '2 x 1', 2.0, 1.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Chelsea', 'Liverpool', '0 x 2', 0.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Chelsea', 'Man City', '1 x 3', 1.0, 3.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Chelsea', 'Man United', '0 x 0', 0.0, 0.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Chelsea', 'Newcastle', '2 x 0', 2.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Chelsea', 'Sheffield United', '4 x 1', 4.0, 1.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Chelsea', 'Southampton', '3 x 3', 3.0, 3.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Chelsea', 'Tottenham', '0 x 0', 0.0, 0.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Chelsea', 'West Brom', '2 x 5', 2.0, 5.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Chelsea', 'West Ham', '3 x 0', 3.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Chelsea', 'Wolves', '0 x 0', 0.0, 0.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Crystal Palace', 'Arsenal', '1 x 3', 1.0, 3.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Crystal Palace', 'Aston Villa', '3 x 2', 3.0, 2.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Crystal Palace', 'Brighton', '1 x 1', 1.0, 1.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Crystal Palace', 'Burnley', '0 x 3', 0.0, 3.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Crystal Palace', 'Chelsea', '1 x 4', 1.0, 4.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Crystal Palace', 'Everton', '1 x 2', 1.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Crystal Palace', 'Fulham', '0 x 0', 0.0, 0.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Crystal Palace', 'Leeds', '4 x 1', 4.0, 1.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Crystal Palace', 'Leicester', '1 x 1', 1.0, 1.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Crystal Palace', 'Liverpool', '0 x 7', 0.0, 7.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Crystal Palace', 'Man City', '0 x 2', 0.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Crystal Palace', 'Man United', '0 x 0', 0.0, 0.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Crystal Palace', 'Newcastle', '0 x 2', 0.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Crystal Palace', 'Sheffield United', '2 x 0', 2.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Crystal Palace', 'Southampton', '1 x 0', 1.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Crystal Palace', 'Tottenham', '1 x 1', 1.0, 1.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Crystal Palace', 'West Brom', '1 x 0', 1.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Crystal Palace', 'West Ham', '2 x 3', 2.0, 3.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Crystal Palace', 'Wolves', '1 x 0', 1.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Everton', 'Arsenal', '2 x 1', 2.0, 1.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Everton', 'Aston Villa', '1 x 2', 1.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Everton', 'Brighton', '4 x 2', 4.0, 2.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Everton', 'Burnley', '1 x 2', 1.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Everton', 'Chelsea', '1 x 0', 1.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Everton', 'Crystal Palace', '1 x 1', 1.0, 1.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Everton', 'Fulham', '0 x 2', 0.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Everton', 'Leeds', '0 x 1', 0.0, 1.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Everton', 'Leicester', '1 x 1', 1.0, 1.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Everton', 'Liverpool', '2 x 2', 2.0, 2.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Everton', 'Man City', '1 x 3', 1.0, 3.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Everton', 'Man United', '1 x 3', 1.0, 3.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Everton', 'Newcastle', '0 x 2', 0.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Everton', 'Sheffield United', '0 x 1', 0.0, 1.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Everton', 'Southampton', '1 x 0', 1.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Everton', 'Tottenham', '2 x 2', 2.0, 2.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Everton', 'West Brom', '5 x 2', 5.0, 2.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Everton', 'West Ham', '0 x 1', 0.0, 1.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Everton', 'Wolves', '1 x 0', 1.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Fulham', 'Arsenal', '0 x 3', 0.0, 3.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Fulham', 'Aston Villa', '0 x 3', 0.0, 3.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Fulham', 'Brighton', '0 x 0', 0.0, 0.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Fulham', 'Burnley', '0 x 2', 0.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Fulham', 'Chelsea', '0 x 1', 0.0, 1.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Fulham', 'Crystal Palace', '1 x 2', 1.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Fulham', 'Everton', '2 x 3', 2.0, 3.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Fulham', 'Leeds', '1 x 2', 1.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Fulham', 'Leicester', '0 x 2', 0.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Fulham', 'Liverpool', '1 x 1', 1.0, 1.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Fulham', 'Man City', '0 x 3', 0.0, 3.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Fulham', 'Man United', '1 x 2', 1.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Fulham', 'Newcastle', '0 x 2', 0.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Fulham', 'Sheffield United', '1 x 0', 1.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Fulham', 'Southampton', '0 x 0', 0.0, 0.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Fulham', 'Tottenham', '0 x 1', 0.0, 1.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Fulham', 'West Brom', '2 x 0', 2.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Fulham', 'West Ham', '0 x 0', 0.0, 0.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Fulham', 'Wolves', '0 x 1', 0.0, 1.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Leeds', 'Arsenal', '0 x 0', 0.0, 0.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Leeds', 'Aston Villa', '0 x 1', 0.0, 1.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Leeds', 'Brighton', '0 x 1', 0.0, 1.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Leeds', 'Burnley', '1 x 0', 1.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Leeds', 'Chelsea', '0 x 0', 0.0, 0.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Leeds', 'Crystal Palace', '2 x 0', 2.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Leeds', 'Everton', '1 x 2', 1.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Leeds', 'Fulham', '4 x 3', 4.0, 3.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Leeds', 'Leicester', '1 x 4', 1.0, 4.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Leeds', 'Liverpool', '1 x 1', 1.0, 1.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Leeds', 'Man City', '1 x 1', 1.0, 1.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Leeds', 'Man United', '0 x 0', 0.0, 0.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Leeds', 'Newcastle', '5 x 2', 5.0, 2.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Leeds', 'Sheffield United', '2 x 1', 2.0, 1.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Leeds', 'Southampton', '3 x 0', 3.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Leeds', 'Tottenham', '3 x 1', 3.0, 1.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Leeds', 'West Brom', '3 x 1', 3.0, 1.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Leeds', 'West Ham', '1 x 2', 1.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Leeds', 'Wolves', '0 x 1', 0.0, 1.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Leicester', 'Arsenal', '1 x 3', 1.0, 3.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Leicester', 'Aston Villa', '0 x 1', 0.0, 1.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Leicester', 'Brighton', '3 x 0', 3.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Leicester', 'Burnley', '4 x 2', 4.0, 2.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Leicester', 'Chelsea', '2 x 0', 2.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Leicester', 'Crystal Palace', '2 x 1', 2.0, 1.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Leicester', 'Everton', '0 x 2', 0.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Leicester', 'Fulham', '1 x 2', 1.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Leicester', 'Leeds', '1 x 3', 1.0, 3.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Leicester', 'Liverpool', '3 x 1', 3.0, 1.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Leicester', 'Man City', '0 x 2', 0.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Leicester', 'Man United', '2 x 2', 2.0, 2.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Leicester', 'Newcastle', '2 x 4', 2.0, 4.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Leicester', 'Sheffield United', '5 x 0', 5.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Leicester', 'Southampton', '2 x 0', 2.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Leicester', 'Tottenham', '2 x 4', 2.0, 4.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Leicester', 'West Brom', '3 x 0', 3.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Leicester', 'West Ham', '0 x 3', 0.0, 3.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Leicester', 'Wolves', '1 x 0', 1.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Liverpool', 'Arsenal', '3 x 1', 3.0, 1.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Liverpool', 'Aston Villa', '2 x 1', 2.0, 1.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Liverpool', 'Brighton', '0 x 1', 0.0, 1.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Liverpool', 'Burnley', '0 x 1', 0.0, 1.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Liverpool', 'Chelsea', '0 x 1', 0.0, 1.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Liverpool', 'Crystal Palace', '2 x 0', 2.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Liverpool', 'Everton', '0 x 2', 0.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Liverpool', 'Fulham', '0 x 1', 0.0, 1.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Liverpool', 'Leeds', '4 x 3', 4.0, 3.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Liverpool', 'Leicester', '3 x 0', 3.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Liverpool', 'Man City', '1 x 4', 1.0, 4.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Liverpool', 'Man United', '0 x 0', 0.0, 0.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Liverpool', 'Newcastle', '1 x 1', 1.0, 1.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Liverpool', 'Sheffield United', '2 x 1', 2.0, 1.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Liverpool', 'Southampton', '2 x 0', 2.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Liverpool', 'Tottenham', '2 x 1', 2.0, 1.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Liverpool', 'West Brom', '1 x 1', 1.0, 1.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Liverpool', 'West Ham', '2 x 1', 2.0, 1.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Liverpool', 'Wolves', '4 x 0', 4.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Man City', 'Arsenal', '1 x 0', 1.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Man City', 'Aston Villa', '2 x 0', 2.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Man City', 'Brighton', '1 x 0', 1.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Man City', 'Burnley', '5 x 0', 5.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Man City', 'Chelsea', '1 x 2', 1.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Man City', 'Crystal Palace', '4 x 0', 4.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Man City', 'Everton', '5 x 0', 5.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Man City', 'Fulham', '2 x 0', 2.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Man City', 'Leeds', '1 x 2', 1.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Man City', 'Leicester', '2 x 5', 2.0, 5.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Man City', 'Liverpool', '1 x 1', 1.0, 1.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Man City', 'Man United', '0 x 2', 0.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Man City', 'Newcastle', '2 x 0', 2.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Man City', 'Sheffield United', '1 x 0', 1.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Man City', 'Southampton', '5 x 2', 5.0, 2.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Man City', 'Tottenham', '3 x 0', 3.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Man City', 'West Brom', '1 x 1', 1.0, 1.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Man City', 'West Ham', '2 x 1', 2.0, 1.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Man City', 'Wolves', '4 x 1', 4.0, 1.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Man United', 'Arsenal', '0 x 1', 0.0, 1.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Man United', 'Aston Villa', '2 x 1', 2.0, 1.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Man United', 'Brighton', '2 x 1', 2.0, 1.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Man United', 'Burnley', '3 x 1', 3.0, 1.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Man United', 'Chelsea', '0 x 0', 0.0, 0.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Man United', 'Crystal Palace', '1 x 3', 1.0, 3.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Man United', 'Everton', '3 x 3', 3.0, 3.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Man United', 'Fulham', '1 x 1', 1.0, 1.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Man United', 'Leeds', '6 x 2', 6.0, 2.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Man United', 'Leicester', '1 x 2', 1.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Man United', 'Liverpool', '2 x 4', 2.0, 4.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Man United', 'Man City', '0 x 0', 0.0, 0.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Man United', 'Newcastle', '3 x 1', 3.0, 1.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Man United', 'Sheffield United', '1 x 2', 1.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Man United', 'Southampton', '9 x 0', 9.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Man United', 'Tottenham', '1 x 6', 1.0, 6.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Man United', 'West Brom', '1 x 0', 1.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Man United', 'West Ham', '1 x 0', 1.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Man United', 'Wolves', '1 x 0', 1.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Newcastle', 'Arsenal', '0 x 2', 0.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Newcastle', 'Aston Villa', '1 x 1', 1.0, 1.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Newcastle', 'Brighton', '0 x 3', 0.0, 3.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Newcastle', 'Burnley', '3 x 1', 3.0, 1.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Newcastle', 'Chelsea', '0 x 2', 0.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Newcastle', 'Crystal Palace', '1 x 2', 1.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Newcastle', 'Everton', '2 x 1', 2.0, 1.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Newcastle', 'Fulham', '1 x 1', 1.0, 1.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Newcastle', 'Leeds', '1 x 2', 1.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Newcastle', 'Leicester', '1 x 2', 1.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Newcastle', 'Liverpool', '0 x 0', 0.0, 0.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Newcastle', 'Man City', '3 x 4', 3.0, 4.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Newcastle', 'Man United', '1 x 4', 1.0, 4.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Newcastle', 'Sheffield United', '1 x 0', 1.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Newcastle', 'Southampton', '3 x 2', 3.0, 2.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Newcastle', 'Tottenham', '2 x 2', 2.0, 2.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Newcastle', 'West Brom', '2 x 1', 2.0, 1.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Newcastle', 'West Ham', '3 x 2', 3.0, 2.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Newcastle', 'Wolves', '1 x 1', 1.0, 1.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Sheffield United', 'Arsenal', '0 x 3', 0.0, 3.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Sheffield United', 'Aston Villa', '1 x 0', 1.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Sheffield United', 'Brighton', '1 x 0', 1.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Sheffield United', 'Burnley', '1 x 0', 1.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Sheffield United', 'Chelsea', '1 x 2', 1.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Sheffield United', 'Crystal Palace', '0 x 2', 0.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Sheffield United', 'Everton', '0 x 1', 0.0, 1.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Sheffield United', 'Fulham', '1 x 1', 1.0, 1.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Sheffield United', 'Leeds', '0 x 1', 0.0, 1.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Sheffield United', 'Leicester', '1 x 2', 1.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Sheffield United', 'Liverpool', '0 x 2', 0.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Sheffield United', 'Man City', '0 x 1', 0.0, 1.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Sheffield United', 'Man United', '2 x 3', 2.0, 3.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Sheffield United', 'Newcastle', '1 x 0', 1.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Sheffield United', 'Southampton', '0 x 2', 0.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Sheffield United', 'Tottenham', '1 x 3', 1.0, 3.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Sheffield United', 'West Brom', '2 x 1', 2.0, 1.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Sheffield United', 'West Ham', '0 x 1', 0.0, 1.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Sheffield United', 'Wolves', '0 x 2', 0.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Southampton', 'Arsenal', '1 x 3', 1.0, 3.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Southampton', 'Aston Villa', '0 x 1', 0.0, 1.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Southampton', 'Brighton', '1 x 2', 1.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Southampton', 'Burnley', '3 x 2', 3.0, 2.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Southampton', 'Chelsea', '1 x 1', 1.0, 1.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Southampton', 'Crystal Palace', '3 x 1', 3.0, 1.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Southampton', 'Everton', '2 x 0', 2.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Southampton', 'Fulham', '3 x 1', 3.0, 1.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Southampton', 'Leeds', '0 x 2', 0.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Southampton', 'Leicester', '1 x 1', 1.0, 1.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Southampton', 'Liverpool', '1 x 0', 1.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Southampton', 'Man City', '0 x 1', 0.0, 1.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Southampton', 'Man United', '2 x 3', 2.0, 3.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Southampton', 'Newcastle', '2 x 0', 2.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Southampton', 'Sheffield United', '3 x 0', 3.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Southampton', 'Tottenham', '2 x 5', 2.0, 5.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Southampton', 'West Brom', '2 x 0', 2.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Southampton', 'West Ham', '0 x 0', 0.0, 0.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Southampton', 'Wolves', '1 x 2', 1.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Tottenham', 'Arsenal', '2 x 0', 2.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Tottenham', 'Aston Villa', '1 x 2', 1.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Tottenham', 'Brighton', '2 x 1', 2.0, 1.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Tottenham', 'Burnley', '4 x 0', 4.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Tottenham', 'Chelsea', '0 x 1', 0.0, 1.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Tottenham', 'Crystal Palace', '4 x 1', 4.0, 1.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Tottenham', 'Everton', '0 x 1', 0.0, 1.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Tottenham', 'Fulham', '1 x 1', 1.0, 1.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Tottenham', 'Leeds', '3 x 0', 3.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Tottenham', 'Leicester', '0 x 2', 0.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Tottenham', 'Liverpool', '1 x 3', 1.0, 3.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Tottenham', 'Man City', '2 x 0', 2.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Tottenham', 'Man United', '1 x 3', 1.0, 3.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Tottenham', 'Newcastle', '1 x 1', 1.0, 1.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Tottenham', 'Sheffield United', '4 x 0', 4.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Tottenham', 'Southampton', '2 x 1', 2.0, 1.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Tottenham', 'West Brom', '2 x 0', 2.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Tottenham', 'West Ham', '3 x 3', 3.0, 3.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Tottenham', 'Wolves', '2 x 0', 2.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('West Brom', 'Arsenal', '0 x 4', 0.0, 4.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('West Brom', 'Aston Villa', '0 x 3', 0.0, 3.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('West Brom', 'Brighton', '1 x 0', 1.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('West Brom', 'Burnley', '0 x 0', 0.0, 0.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('West Brom', 'Chelsea', '3 x 3', 3.0, 3.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('West Brom', 'Crystal Palace', '1 x 5', 1.0, 5.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('West Brom', 'Everton', '0 x 1', 0.0, 1.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('West Brom', 'Fulham', '2 x 2', 2.0, 2.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('West Brom', 'Leeds', '0 x 5', 0.0, 5.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('West Brom', 'Leicester', '0 x 3', 0.0, 3.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('West Brom', 'Liverpool', '1 x 2', 1.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('West Brom', 'Man City', '0 x 5', 0.0, 5.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('West Brom', 'Man United', '1 x 1', 1.0, 1.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('West Brom', 'Newcastle', '0 x 0', 0.0, 0.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('West Brom', 'Sheffield United', '1 x 0', 1.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('West Brom', 'Southampton', '3 x 0', 3.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('West Brom', 'Tottenham', '0 x 1', 0.0, 1.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('West Brom', 'West Ham', '1 x 3', 1.0, 3.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('West Brom', 'Wolves', '1 x 1', 1.0, 1.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('West Ham', 'Arsenal', '3 x 3', 3.0, 3.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('West Ham', 'Aston Villa', '2 x 1', 2.0, 1.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('West Ham', 'Brighton', '2 x 2', 2.0, 2.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('West Ham', 'Burnley', '1 x 0', 1.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('West Ham', 'Chelsea', '0 x 1', 0.0, 1.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('West Ham', 'Crystal Palace', '1 x 1', 1.0, 1.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('West Ham', 'Everton', '0 x 1', 0.0, 1.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('West Ham', 'Fulham', '1 x 0', 1.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('West Ham', 'Leeds', '2 x 0', 2.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('West Ham', 'Leicester', '3 x 2', 3.0, 2.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('West Ham', 'Liverpool', '1 x 3', 1.0, 3.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('West Ham', 'Man City', '1 x 1', 1.0, 1.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('West Ham', 'Man United', '1 x 3', 1.0, 3.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('West Ham', 'Newcastle', '0 x 2', 0.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('West Ham', 'Sheffield United', '3 x 0', 3.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('West Ham', 'Southampton', '3 x 0', 3.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('West Ham', 'Tottenham', '2 x 1', 2.0, 1.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('West Ham', 'West Brom', '2 x 1', 2.0, 1.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('West Ham', 'Wolves', '4 x 0', 4.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Wolves', 'Arsenal', '2 x 1', 2.0, 1.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Wolves', 'Aston Villa', '0 x 1', 0.0, 1.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Wolves', 'Brighton', '2 x 1', 2.0, 1.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Wolves', 'Burnley', '0 x 4', 0.0, 4.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Wolves', 'Chelsea', '2 x 1', 2.0, 1.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Wolves', 'Crystal Palace', '2 x 0', 2.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Wolves', 'Everton', '1 x 2', 1.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Wolves', 'Fulham', '1 x 0', 1.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Wolves', 'Leeds', '1 x 0', 1.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Wolves', 'Leicester', '0 x 0', 0.0, 0.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Wolves', 'Liverpool', '0 x 1', 0.0, 1.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Wolves', 'Man City', '1 x 3', 1.0, 3.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Wolves', 'Man United', '1 x 2', 1.0, 2.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Wolves', 'Newcastle', '1 x 1', 1.0, 1.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Wolves', 'Sheffield United', '1 x 0', 1.0, 0.0, 'Win');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Wolves', 'Southampton', '1 x 1', 1.0, 1.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Wolves', 'Tottenham', '1 x 1', 1.0, 1.0, 'Draw');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Wolves', 'West Brom', '2 x 3', 2.0, 3.0, 'Lose');
INSERT INTO "Tabela Premier League 2021" (home_team, away_team, score, home_team_goals, away_team_goals, result) VALUES ('Wolves', 'West Ham', '2 x 3', 2.0, 3.0, 'Lose');

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
